const fruit = [];
fruit.push("mango", "apple", "banana");
console.log(fruit);
fruit.push("papaya");
console.log(fruit);
fruit.pop();
console.log(fruit);
fruit.unshift("orange");
console.log(fruit);
fruit.unshift("Grapes");
console.log(fruit);
fruit.shift();
console.log(fruit);
